"""empty message

Revision ID: bf7ece97d806
Revises: 
Create Date: 2023-10-24 17:56:42.329375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ece97d806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('franchise')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('franchise', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('franchise')

    op.create_table('franchise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('franchise', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
